### ISSUE TITLE
packagecloud.io/grafana package not found

### ISSUE THREAD

**Issue by verschoof** [idealista/grafana-role#14]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

```
TASK [idealista.grafana-role : GRAFANA | Debian grafana repo] ******************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The repository 'https://packagecloud.io/grafana/stable/debian stretch Release' does not have a Release file.
fatal: [monitoring.future500.loc]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_apt_repository_payload_VMuOro/__main__.py\", line 554, in <module>\n  File \"/tmp/ansible_apt_repository_payload_VMuOro/__main__.py\", line 546, in main\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 464, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:The repository 'https://packagecloud.io/grafana/stable/debian stretch Release' does not have a Release file.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### Steps to Reproduce

Just use the role? :)

**Expected behavior:** [What you expect to happen]

I expected to download the package from https://packagecloud.io/grafana/

**Actual behavior:** [What actually happens]

Error occurs, looks like https://packagecloud.io/grafana/ package is deleted?

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Latest

**Comment by frantsao** [comment]
Fixed in 1.2.1 release.
